name: "RUN ITDE-GET"

on:
  schedule:
    - cron:  '0 */12 * * *' # Every 12 Hours 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Setup Python
         uses: actions/setup-python@v1
         with:
          python-version: 3.9
       - name: Install requirements
         run: pip3 install -r requirements.txt
       - name: Install Git LFS
         run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
       - name: Install LFS
         run: git lfs install
       - name: RUN ITDE-GET
         run: python3 ITDE-Get.py
       - uses: stefanzweifel/git-auto-commit-action@v4
         continue-on-error: true
         with:
          commit_message: 'Auto: RUN ITDE-Get'
          repository: .
          commit_user_name: New-dev0
          commit_user_email: Newdev0@outlook.com
          commit_author: Devesh Pal <Newdev0@outlook.com>
          
